In [1]:
import numpy as np
import scipy as sp

In [2]:
%precision 3

'%.3f'

In [3]:
fish_data=np.array([2,3,3,4,4,4,4,5,5,6])
fish_data

array([2, 3, 3, 4, 4, 4, 4, 5, 5, 6])

In [4]:
sp.sum(fish_data)

<ipython-input-4-700af4cfa22b>:1: DeprecationWarning: scipy.sum is deprecated and will be removed in SciPy 2.0.0, use numpy.sum instead
  sp.sum(fish_data)


40

In [5]:
len(fish_data)

10

In [6]:
N=len(fish_data)
sum_value=np.sum(fish_data)
mu=sum_value/N
mu

4.0

In [7]:
sp.mean(fish_data)

<ipython-input-7-0144c156ee1d>:1: DeprecationWarning: scipy.mean is deprecated and will be removed in SciPy 2.0.0, use numpy.mean instead
  sp.mean(fish_data)


4.0

In [8]:
sp.sum((fish_data-mu)**2)/N

<ipython-input-8-89d9144259f2>:1: DeprecationWarning: scipy.sum is deprecated and will be removed in SciPy 2.0.0, use numpy.sum instead
  sp.sum((fish_data-mu)**2)/N


1.2

In [10]:
sp.var(fish_data,ddof=0) #표본분산

<ipython-input-10-7a5a481341da>:1: DeprecationWarning: scipy.var is deprecated and will be removed in SciPy 2.0.0, use numpy.var instead
  sp.var(fish_data,ddof=0) #표본분산


1.2

In [12]:
sigma_2=sp.var(fish_data,ddof=1) #불편분산
sigma_2

<ipython-input-12-238dc9b34e0e>:1: DeprecationWarning: scipy.var is deprecated and will be removed in SciPy 2.0.0, use numpy.var instead
  sigma_2=sp.var(fish_data,ddof=1) #불편분산


1.3333333333333333

In [15]:
sigma=sp.sqrt(sigma_2)
sigma

<ipython-input-15-039b4d368781>:1: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  sigma=sp.sqrt(sigma_2)


1.1547005383792515

In [21]:
sp.std(fish_data,ddof=1)

<ipython-input-21-4dab285be8f2>:1: DeprecationWarning: scipy.std is deprecated and will be removed in SciPy 2.0.0, use numpy.std instead
  sp.std(fish_data,ddof=1)


1.1547005383792515

In [19]:
#표준화: 데이터 평균을 0, 표준편차(분산)을 1로 변환
fish_data-mu


array([-2., -1., -1.,  0.,  0.,  0.,  0.,  1.,  1.,  2.])

In [18]:
#표준편차 1로 변환: 데이터를 표준편차로 나누기
fish_data/sigma

array([1.732, 2.598, 2.598, 3.464, 3.464, 3.464, 3.464, 4.33 , 4.33 ,
       5.196])

In [20]:
sp.std(fish_data/sigma,ddof=1)

<ipython-input-20-e6625fce1a17>:1: DeprecationWarning: scipy.std is deprecated and will be removed in SciPy 2.0.0, use numpy.std instead
  sp.std(fish_data/sigma,ddof=1)


1.0

In [22]:
#데이터 표준화
standard=(fish_data-mu)/sigma
standard

array([-1.732, -0.866, -0.866,  0.   ,  0.   ,  0.   ,  0.   ,  0.866,
        0.866,  1.732])

In [23]:
sp.amax(fish_data)

<ipython-input-23-f8f5d27228e4>:1: DeprecationWarning: scipy.amax is deprecated and will be removed in SciPy 2.0.0, use numpy.amax instead
  sp.amax(fish_data)


6

In [24]:
sp.amin(fish_data)

<ipython-input-24-3abba0e26dc4>:1: DeprecationWarning: scipy.amin is deprecated and will be removed in SciPy 2.0.0, use numpy.amin instead
  sp.amin(fish_data)


2

In [25]:
sp.median(fish_data)

<ipython-input-25-a290ea0f17da>:1: DeprecationWarning: scipy.median is deprecated and will be removed in SciPy 2.0.0, use numpy.median instead
  sp.median(fish_data)


4.0

In [26]:
from scipy import stats

In [27]:
#사분위수 출력
fish_data_3=np.array([1,2,3,4,5,6,7,8,9])
stats.scoreatpercentile(fish_data_3,25)

3.0

In [28]:
stats.scoreatpercentile(fish_data_3,75)

7.0