In [ ]:
6//3

2

In [ ]:
def sample_function(data):
  return ((data+2)*4)

sample_function(4)

24

In [ ]:
class sample_class:
  def __init__(self, data1, data2):
    self.data1=data1
    self.data2=data2

  def method2(self):
    return(self.data1 + self.data2)

In [ ]:
sample_instance=sample_class(2, 3)

sample_instance.method2()

5

In [ ]:
for i in range(0,3):
  print(i)

0
1
2


In [ ]:
import numpy as np
import pandas as pd

In [ ]:
sample_list=[1,2,3,4,5]
sample_list

[1, 2, 3, 4, 5]

In [ ]:
sample_array=np.array([1,2,3,4,5])
sample_array

array([1, 2, 3, 4, 5])

In [ ]:
sample_array+2


array([3, 4, 5, 6, 7])

In [ ]:
sample_array*2

array([ 2,  4,  6,  8, 10])

In [ ]:
sample_array2=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [ ]:
sample_array2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
sample_array2.shape

(2, 5)

In [ ]:
np.arange(start=1,stop=6,step=1)

array([1, 2, 3, 4, 5])

In [ ]:
np.arange(start=0.2,stop=1,step=0.2)

array([0.2, 0.4, 0.6, 0.8])

In [ ]:
np.arange(0.1,0.8,0.2)

array([0.1, 0.3, 0.5, 0.7])

In [ ]:
np.tile(0,5)

array([0, 0, 0, 0, 0])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros([2,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
d1_array=np.array([1,2,3,4,5])
d1_array[1]

2

In [ ]:
d1_array[1:3]

array([2, 3])

In [ ]:
d2_array=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [ ]:
d2_array[0,3]

4

In [ ]:
d2_array[1,1:3]

array([7, 8])

In [ ]:
sample_df=pd.DataFrame({
    'col1':sample_array,
    'col2':sample_array*2,
    'col3':["A","B","C","D","E"]
})
print(sample_df)

   col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    E


In [ ]:
sample_df

col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    E

In [ ]:
df_1=pd.DataFrame({
    'col1':np.array([1,2,3]),
    'col2':np.array(["A","B","C"])
})
df_2=pd.DataFrame({
    'col1':np.array([4,5,6]),
    'col2':np.array(["D","E","F"])
})

In [ ]:
pd.concat([df_1,df_2])

col1 col2
0     1    A
1     2    B
2     3    C
0     4    D
1     5    E
2     6    F

In [ ]:
pd.concat([df_1,df_2],axis=1)

col1 col2  col1 col2
0     1    A     4    D
1     2    B     5    E
2     3    C     6    F

In [ ]:
sample_df

col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    E

In [ ]:
sample_df.col2

0     2
1     4
2     6
3     8
4    10
Name: col2, dtype: int64

In [ ]:
sample_df[["col1","col2"]]

col1  col2
0     1     2
1     2     4
2     3     6
3     4     8
4     5    10

In [ ]:
sample_df.head(3)

col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C

In [ ]:
sample_df.query('index==0')

col1  col2 col3
0     1     2    A

In [ ]:
sample_df.query('col3=="A"')

col1  col2 col3
0     1     2    A

In [ ]:
sample_df.query('col3=="A"|col3=="D"')

col1  col2 col3
0     1     2    A
3     4     8    D

In [ ]:
sample_df.query('col3=="A"&col1==3')

Empty DataFrame
Columns: [col1, col2, col3]
Index: []

In [ ]:
#col3==A에 해당하는 열 중 col2, col3만 출력
sample_df.query('col3=="A"')[["col2","col3"]]

col2 col3
0     2    A

In [ ]:
type(sample_df)

pandas.core.frame.DataFrame

In [ ]:
type(sample_df.col1)

pandas.core.series.Series

In [ ]:
np.array(sample_df.col1)

array([1, 2, 3, 4, 5])

In [ ]:
sample_df.col1.values

array([1, 2, 3, 4, 5])

In [ ]:
help(sample_df.query)